package com.bulknews.agent.output

import com.bulknews.agent.model.NewsCollection
import mu.KotlinLogging
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

private val logger = KotlinLogging.logger {}

class MarkdownGenerator {

    fun generateMarkdown(newsCollections: List<NewsCollection>): String {
        logger.info { "Generating markdown for ${newsCollections.size} news collections" }
        
        val sb = StringBuilder()
        
        // Header
        sb.appendLine("# Daily News Summary")
        sb.appendLine()
        sb.appendLine("*Generated on ${LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))}*")
        sb.appendLine()
        sb.appendLine("---")
        sb.appendLine()
        
        // Table of Contents
        sb.appendLine("## Table of Contents")
        sb.appendLine()
        newsCollections.forEachIndexed { index, collection ->
            sb.appendLine("${index + 1}. [${collection.topic}](#${collection.topic.lowercase().replace(" ", "-")})")
        }
        sb.appendLine()
        sb.appendLine("---")
        sb.appendLine()
        
        // News sections
        newsCollections.forEach { collection ->
            sb.append(generateTopicSection(collection))
        }
        
        // Footer
        sb.appendLine("---")
        sb.appendLine()
        sb.appendLine("*This news summary was automatically generated by BulkNews Agent*")
        
        return sb.toString()
    }

    private fun generateTopicSection(collection: NewsCollection): String {
        val sb = StringBuilder()
        
        sb.appendLine("## ${collection.topic}")
        sb.appendLine()
        
        if (collection.articles.isEmpty()) {
            sb.appendLine("*No articles found for this topic.*")
            sb.appendLine()
        } else {
            collection.articles.forEachIndexed { index, article ->
                sb.appendLine("### ${index + 1}. ${article.title}")
                sb.appendLine()
                sb.appendLine("**Summary:** ${article.summary}")
                sb.appendLine()
                sb.appendLine("**Source:** ${article.source}")
                sb.appendLine()
                sb.appendLine("**Published:** ${article.publishedDate}")
                sb.appendLine()
                sb.appendLine("**Link:** [Read more](${article.url})")
                sb.appendLine()
                sb.appendLine("---")
                sb.appendLine()
            }
        }
        
        return sb.toString()
    }

    fun saveToFile(content: String, fileName: String = "news-summary.md"): String {
        logger.info { "Saving markdown to file: $fileName" }
        val file = java.io.File(fileName)
        file.writeText(content)
        logger.info { "Markdown saved to: ${file.absolutePath}" }
        return file.absolutePath
    }
}
