[versions]
kotlin = "2.3.0"
junit-jupiter-engine = "5.12.1"
jsoup = "1.18.2"
kotlinx-serialization = "1.8.0"
coroutines = "1.10.1"
koog = "0.6.0"
slack = "1.45.3"

[libraries]
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter-engine" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
koog-agents = { module = "ai.koog:koog-agents", version.ref = "koog" }
slack-api-client = { module = "com.slack.api:slack-api-client", version.ref = "slack" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
